name: .NET CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - *

jobs:
# Build and test on .NET Core
  dotnet-core-ci:
    name: .NET Core - test
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: nuget restore

      - name: Build solution
        run: dotnet build

      - name: Run tests
        run: dotnet test

      # - name: Run linter
      #   run: dotnet format --verify-no-changes

  # Build and test on .NET Framework
  dotnet-framework-ci:
    name: .NET Framework - test
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Set up VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Install dependencies
        run: nuget restore

      - name: Build DuoApiTest solution
        run: msbuild.exe duo_api_csharp.sln

      - name: Run Tests dll
        run: vstest.console.exe .\DuoApi.Tests\bin\Debug\net6.0\DuoApi.Tests.dll
